Adding troubleshooting topics
osisoft/PI-Adapter-DNP3-Docs pull request #24
Opened 2021-03-31 00:44 UTC by TinaUll

Hi @cmorgan-osi and @ewillis-osi, I drafted a troubleshooting section for the DNP3 adapter. Do you mind taking a look and helping me with the data source and data selection parameters that should be be checked when troubleshooting? Thank you!
(Will also create this section for RDBMS)

2021-03-31 21:30 UTC, osisoft-mbishop requested changes
I left a couple of comments, but nothing major.

2021-03-31 21:30 UTC, osisoft-mbishop commented on content/troubleshooting/troubleshoot-pi-adapter-for-dnp3.md
> +2. Navigate to [data selection configuration](xref:PIAdapterForDNP3DataSelectionConfiguration) and verify the following for each configured data selection item below:
This construction is awkward. 

```suggestion
2. Navigate to [data selection configuration](xref:PIAdapterForDNP3DataSelectionConfiguration) and verify that the following data selection items are correct:
```

2021-03-31 21:30 UTC, osisoft-mbishop commented on content/troubleshooting/troubleshoot-pi-adapter-for-dnp3.md
> +3. Navigate to [egress endpoints configuration](xref:EgressEndpointsConfiguration) and verify each configured endpoint's **Endpoint** property and credentials are correct.
This sentence is confusing because its construction isn't parallel. My suggestion:

```suggestion
3. Navigate to [egress endpoints configuration](xref:EgressEndpointsConfiguration). For each configured endpoint, verify that the **Endpoint** and authentication properties are correct.
```

2021-04-23 20:05 UTC, TinaUll commented on content/troubleshooting/troubleshoot-pi-adapter-for-dnp3.md
> +1. Navigate to [data source configuration](xref:PIAdapterForDNP3DataSourceConfiguration) and verify that <!-- Insert data source parameters that need to be checked --> are correct.
```suggestion
1. Navigate to [data source configuration](xref:PIAdapterForDNP3DataSourceConfiguration) and verify that <!-- Insert data source parameters that need to be checked  TEST--> are correct.
```

2021-05-07 17:40 UTC, merged