295396 update install adapter section
osisoft/PI-Adapter-DNP3-Docs pull request #43
Opened 2022-02-19 01:04 UTC by osisoft-mbishop

2022-02-22 17:30 UTC, KNyce71 commented on content/main/shared-content/installation/install-using-docker.md
> +**Note:** If you want to use Docker, you must be familiar with the underlying technology and have determined that it is appropriate for your planned use of the adapter. Docker is not required to use
```suggestion
**Note:** If you want to use Docker, OSIsoft recommends that you be both familiar with the underlying technology and have determined that it is appropriate for your planned use of the adapter. Docker is not required to use the adapter.
```

2022-02-22 17:46 UTC, KNyce71 reviewed
One minor suggestion identical to the one in PR #36.

2022-02-23 23:18 UTC, rmuolic commented on content/main/shared-content/installation/install-using-docker.md
> +**Note:** If you want to use Docker, you must be familiar with the underlying technology and have determined that it is appropriate for your planned use of the adapter. Docker is not required to use
```suggestion
**Note:** Installation using Docker is only recommended for users proficient with Docker. Docker is not required to use the adapter.
```

2022-02-23 23:24 UTC, rmuolic commented on content/main/shared-content/installation/install-using-docker.md
> +**Note:** If you want to use Docker, you must be familiar with the underlying technology and have determined that it is appropriate for your planned use of the adapter. Docker is not required to use
```suggestion
 **Note:** Installation using Docker is only recommended for users proficient with Docker. Docker is not required to use the adapter.
```

2022-02-23 23:34 UTC, rmuolic commented on content/main/shared-content/installation/install-using-docker.md
> +**Note:** If you want to use Docker, you must be familiar with the underlying technology and have determined that it is appropriate for your planned use of the adapter. Docker is not required to use
```suggestion
**Note:** The use of Docker is only recommended if your environment requires it. Only users proficient with Docker should use it to install the adapter. Docker is not required to use the adapter.
```

2022-02-23 23:36 UTC, rmuolic commented on content/toc.yml
>    - topicUid: UninstallTheAdapter
```suggestion
  - topicUid: InstallUsingDocker
  - topicUid: UpgradeTheAdapter
  - topicUid: UninstallTheAdapter
```

2022-02-23 23:37 UTC, rmuolic requested changes
Minor changes.

2022-02-23 23:41 UTC, osisoft-mbishop commented on content/main/shared-content/installation/install-using-docker.md
> +**Note:** If you want to use Docker, you must be familiar with the underlying technology and have determined that it is appropriate for your planned use of the adapter. Docker is not required to use
Rainier and I found a better way to word this section.

2022-02-23 23:48 UTC, rmuolic approved these changes

2022-02-23 23:49 UTC, merged